name: vietnamese_fish_sauce_app
description: "Vietnamese fish sauce e-commerce mobile application with Clean Architecture and zero-warning policy"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependencies in alphabetical order
  bloc: ^9.0.1
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev dependencies in alphabetical order
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Leaf folders only (each contains actual files)
    - assets/begin_login_register/main/
    - assets/begin_login_register/register/
    - assets/login/
    - assets/add_to_cart/
    - assets/figma_exports/
    - assets/figma_temp/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # Custom fonts - COMMENTED OUT until font files are downloaded
  # To enable: Download fonts from Google Fonts and place in assets/fonts/
  # See assets/fonts/README.md for instructions
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Gayathri
  #     fonts:
  #       - asset: assets/fonts/Gayathri-Bold.ttf
  #         weight: 700