name: vietnamese_fish_sauce_app
description: "Vietnamese fish sauce e-commerce mobile application with Clean Architecture and zero-warning policy"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  cupertino_icons: ^1.0.8

  # State Management - Bloc (replacing Provider for UI state)
  flutter_bloc: ^9.0.0
  bloc_concurrency: 0.3.0

  # Networking - Dio with interceptors and connection pooling
  dio: ^5.4.3+1

  # Local Storage - SharedPreferences with secure storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Navigation - Go Router 12+
  go_router: ^14.2.3

  # Dependency Injection - GetIt
  get_it: ^7.7.0
  injectable: ^2.5.0

  # Image Loading - Cached network image with optimization
  cached_network_image: ^3.4.0

  # Performance optimizations
  flutter_staggered_animations: ^1.1.1

  # UI Components
  flutter_svg: ^2.0.10+1

  # Utilities
  intl: 0.20.2
  uuid: ^4.4.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Leaf folders only (each contains actual files)
    - assets/begin_login_register/main/
    - assets/begin_login_register/register/
    - assets/login/
    - assets/add_to_cart/
    - assets/main_page/
    - assets/product_page/
    - assets/product_detail/
    - assets/cart_page/
    - assets/finalize_order/
    - assets/profile_customer_service_announcement/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
