name: mgf_fish_sauce_app
description: Vietnamese Fish Sauce E-commerce Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pinput: ^3.0.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSans-Regular.ttf
  #       - asset: assets/fonts/NotoSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSans-Bold.ttf
  #         weight: 700
